name: hgppdx
favicon: null
layout_spectrum: 0.73464
typography_spectrum: 0.9287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#95abc3'
    - '#dfdccb'
    - '#3c4043'
    - '#12130e'
    - '#c14d5a'
  brandStrength: 0.25
  lightness: 0.2426598584279418
  saturation: 0.07294665928930044
  rhythmicContrast: 0.49715048377402127
purpose: []
